- hosts: masters
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.10.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's ubuntu config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: copies Calico YAML to user's ubuntu home dir
      become_user: ubuntu
      copy:
        src: calico/tigera-operator.yaml
        dest: $HOME/tigera-operator.yaml
        remote_src: no

    - name: copies Calico custom YAML to user's ubuntu home dir
      become_user: ubuntu
      copy:
        src: calico/custom-resources.yaml
        dest: $HOME/custom-resources.yaml
        remote_src: no

    - name: sleep 180 s
      pause:
        seconds: 180

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl create -f tigera-operator.yaml
      args:
        chdir: $HOME

    - name: install Pod network custom
      become: yes
      become_user: ubuntu
      shell: kubectl create -f custom-resources.yaml
      args:
        chdir: $HOME

    - name: sleep 360 s
      pause:
        seconds: 360

    - name: get the token for joining the worker nodes
      become: yes
      become_user: ubuntu
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
